image: maven:3.3.9
pipelines:
  branches:
    master:
      - step: 
          name: Install necessary tools 
          script:
            - echo "Installing docker"
            - curl -fsSL https://get.docker.com -o get-docker.sh
            - sudo sh get-docker.sh
            - sudo groupadd docker
            - sudo usermod -aG docker $USER
            - echo "Installing kubectl"
            - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            - chmod +x kubectl
            - sudo mv kubectl /usr/local/bin

      - step:
          name: Building JAR file using maven
          script:
            - chmod +x mvnw
            - ./maven clean build
          artifacts:
            - ./target/test-classes/QuoraApp-0.0.1-SNAPSHOT.jar
      
      - step:
          name: Building DockerImages
          script:
           -  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
           -  docker build -t anmol44/adexproject .
           -  docker push anmol44/adexproject

      - step:
          name: Deployment in k8s cluster
          script:
            - kubectl config set-cluster <k8s-cluster-name> --server=https://<k8s-api-server>
            - kubectl config set-credentials <cluster-username> --token=$KUBE_TOKEN
            - kubectl config set-context <cluster-context> --cluster=<k8s-cluster-name> --user=<cluster-username>
            - kubectl config use-context <cluster-context>
            - kubectl run adex-test --image=anmol44/adexproject:latest --replicas=2
            - kubectl expose deployment adex-test --type=NodePort --port=8000